### ISSUE TITLE
[TASK] Create Buttons To Navigate Between Durations/Change Calendar Date

### ISSUE THREAD

**Issue by iOlivers** [iOlivers/BrockTimeTable#1]
Buttons need to be made that allow you to flip either between specific durations. 

(Note: This would mean they have to be different buttons for Fall/Winter and Spring/Summer)

Alternatively just add some buttons to change the month on the calendar specifically that are not related to durations
but still allow to the users to see how their timetable differs across different months.

Either way all the buttons would be doing behind the scenes is simply switching the FullCalendar date. It would not be creating or changing any events or timetables.

Buttons should probably be located near the prev/next bar for changing between different timetable options.

**Comment by condyl** [comment]
Made some changes in d48c2f6 which will make the button work for any year.  This will not work for Spring/Summer terms though, but those will need more thought as there can be 8+ different durations.  I am closing this issue for now.
