### ISSUE TITLE
[TASK] Combine overlapping blocked time events

### ISSUE THREAD

**Issue by condyl** [iOlivers/BrockTimeTable#8]
Blocked out times should either combine or be ignored if they are overlapping another blocked out time.  This isn't a major issue in any way, but it would prevent stuff like this from being possible: 
![image](https://github.com/iOlivers/BrockTimeTable/assets/108146005/c3dd24ce-3ee4-4d9e-87bf-bb5e665a4f34)

**Comment by iOlivers** [comment]
Issue has been resolved as part of commit: https://github.com/iOlivers/BrockTimeTable/commit/7a6e1a0ce1cb2afbfc1d68d5b839c5298db37835
